# Generated by Django 3.1.1 on 2020-11-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleados', models.AutoField(db_column='id_empleados', primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
