# Generated by Django 3.1.1 on 2020-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
