# Generated by Django 3.1.2 on 2020-11-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20201103_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
