# Generated by Django 3.1.2 on 2020-11-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20201105_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_producto', models.IntegerField()),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
