# Generated by Django 3.1.2 on 2020-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cod_producto',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
